	.title	swabi	Byte swap, (argument is an integer)
	.ident	/000004/
;
;+
;
; Index		Byte swap an integer
;
; Usage
;
;	swabi(value);
;	int		value;
;
; Description
;
;	Return value byte-swab'ed.
;
; Bugs
;
;-
;
; Edit history
; 000001 09-Jan-80 MM	Initial edit
; 000002 07-Mar-80 MM	Renamed swabi
; 000003 19-Oct-81 MM	.psect
; 000004 15-Jan-02 BQT	Changed for I/D space
;
	.psect	c$code,i,ro

swabi::
	mov	2(sp),r0		; Get value
	swab	r0			; Do it.
	rts	pc
	.end
